### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by KalleHahl** [janikakalliokoski/datastructures-and-algorithms-lab#1]
Project downloaded : 15.2.2023 - 17pm.

- After downloading the project I tested it thoroughly with many expressions using all of the available operators. The calculator works very well and is simple to use. Incorrect inputs give the correct error message and I didn't manage to 'break' the program with any inputs. The only issue I encountered was with negative numbers in expressions e.g. 5+(-5). They gave an index error, but I figured this problem was in your todos and found the 'todo' in the week 4 documentation.
- The code in this project is extremely clean, well commented and understandable. I especially like the way the project uses object oriented programming and separate functions for handling different operators. It makes following the code easy and the usage of separate functions prevents unnecessary nesting, making it even clearer.
- Different functionalities of the program like the shunting yard algorithm are divided in to separate files, good! This further improves the clarity of this project, especially if someone is not familiar at all with how shunting yard calculators work. I'm grasping at straws trying to find constructive criticism for this project since everything is done so well, but one thing I would change is putting the calculator files in a separate calculator folder and the algorithms for parsing and counting the given expression into their own algorithms folder. It would make it easier for someone with no prior knowledge on the subject to immediately see which files are algorithms and which are for the interface.
- Plenty of tests here, good! The tests cover all the operators and incorrect input situations. There are long expressions with many operators, but I would maybe add a few tests which have more parentheses.

Overall, A+ job on this one. Best of luck for the remainder of the course!

**Comment by janikakalliokoski** [comment]
Thank you for your feedback! I will separate the algorithm and interface files into their own folders. That will make my project clearer. Good luck to you too with the rest of the course! :)
