### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by kodtld** [janikakalliokoski/datastructures-and-algorithms-lab#2]
_Ladattu laitteelle 26.02.2023 - 15:20_

Projekti on edennyt erinomaisesti ja on käytännössä jo valmis. Koodi on selkeää ja jaettu loogisesti eri tiedostoihin. Sovellus myös toimii toivotulla tavalla.

**Kommentit**

Testikattavuus on korkea ja koodi läpäisee CI:n.
Kommitit ovat kuvaavasti nimetty ja yleisesti selkeitä.
".coveragerc" tiedoston olisi voinut sisällyttää .gitignoreen.
Help komento olisi voinut mielestäni antaa hiukan laajemmat ohjeet laskimen käytöstä.
Calculator.py tiedostossa oli myös jonkun verran "if if if", "if elif" sijaan.
Variable name ja validity olisi voinut ehkä jakaa kahteen metodiin.

Kokonaisuudessaan projekti oli oikein hienosti toteutettu ja toimi hyvin. Aitoja kehityskohtia oli mielestäni vaikea löytää, kaikki oli selkeää ja loogista.
Hyvää työtä!

**Comment by janikakalliokoski** [comment]
Kiitos palautteesta! Tein oman metodin muuttujan nimen oikeellisuuden varmistamiseen. Kiitos vinkeistä!
